### PR TITLE
field: fix missing optional support

### LINKED ISSUE #94: [bug] proto3 optional fields supported but not implemented
Background here: https://github.com/lyft/protoc-gen-star/issues/75#issuecomment-833165873.

### PR DESCRIPTION
**Pull request by sarthak40**
Fixes #94 & #75.

Adds support for `optional` field presence in the `proto3` syntax.

### CODE REVIEW

**Comment by sarthak40** [comment]
Reviewable! @dkunitsk @akonradi

\cc @glerchundi

**Comment by glerchundi** [comment]
Good job @sarthak40 LGTM

**Review by glerchundi — APPROVED** [review]

**Comment by sarthak40** [comment]
Hm, I attempted integrating this with [`protoc-gen-validate`](https://github.com/envoyproxy/protoc-gen-validate) but it looks like we'll need additional changes to make this work.. more specifically in `Message` & `AST` related stuff.

Currently the generated code is just rendering all `optional` fields as [synthetic one-of](https://github.com/protocolbuffers/protobuf/blob/master/docs/implementing_proto3_presence.md#updating-a-code-generator) fields, as defined in the field presence doc. I am not sure what the best way to integrate this is yet so a short circuit would be an acceptable solution for now.

I'll mark this as a draft for now, till I can make the required changes. Since this is a generation framework, I don't have to worry about updating any templates thank fully (yet)..

**Comment by dkunitsk** [comment]
Hey @sarthak40. Yes, thank you for pointing this out. The [Implementing Proto3 Presence](https://github.com/protocolbuffers/protobuf/blob/master/docs/implementing_proto3_presence.md) doc gives great advice for what API changes are needed. 

Of particular significance is Google's suggestion (per my reading) that, because Synthetic Oneofs *are still oneofs*, helpers like `IsInOneof()` etc should act as though the oneof is real. They propose to add *additional helpers*, e.g. `IsInRealOneof()` etc, to differentiate real and synthetic - I assume by reading [this option](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/descriptor.proto#L238). 

This means in PGV we'd have to switch to these new `Real` methods. Since PGV is on top of regular codegen, treating synthetic oneofs as real is impossible since synthetic oneofs won't generate `case` statements. 

I'm weighing this suggestion with the more obvious and backward-compatible approach of just making the existing `IsInOneof()` etc methods return true only for real oneofs. I'm currently leaning towards the latter.

**Comment by sarthak40** [comment]
@dkunitsk are you certain that we need to expose synthetic oneofs?

According to the doc:
> Avoid generating any oneof-based accessors for the synthetic oneof. Its only purpose is to make reflection-based algorithms work properly if they are not aware of proto3 presence. The synthetic oneof should not appear anywhere in the generated API.

**Comment by sarthak40** [comment]
Given the above, I think the `ast` parser can be updated to account for detecting these synthetic oneofs. My proposal:

1. Update the grapher to detect based on the following conditions if a `oneof` is synthetic or not.
    1. `oneof.Syntax() == Proto3`
    2. `len(oneof.Fields()) == 1`
    3. `oneof.Fields()[0].Proto3Optional() == true`
2. If (1) is true, then we proceed by extracting the `proto3 oneof` field, graphing it & discarding the synthetic oneof.
3. Otherwise its considered to be an actual `oneof` field, and we proceed as planned.
 
Since field presence in `proto3` is now the property of the individual fields, it actually makes this particular change quite transparent to the end users. Nothing existing will break, and they will have to explicitly add support for `proto3 oneof` by checking for `field.Proto3Optional()`.

WDYT?

**Comment by dkunitsk** [comment]
Re the quote: I believe that's more in the same vein as the default codegen not outputting `case` statements for synthetic oneofs. What's more relevant to PGS is the `Updating Reflection` guidance. 

I think I've had some understanding here, and it starts with https://github.com/lyft/protoc-gen-star/pull/85 being the wrong thing to do. PGS cannot support Optional, only the end user of PGS (the plugin author) can do that. As such, the right approach is to allow the user to set this on their end once *they* are ready to differentiate synthetic and real oneofs. This could easily be done with very minor modification to Generator (a new `SupportedFields` field) and letting it be set by way of `InitOption`: https://github.com/lyft/protoc-gen-star/blob/8bc36edf5b43c9b41d15646f1acb8a667aaf317d/generator.go#L29

Now that the onus of Optional support is on the plugin author, the question above IMO is more clear: if the user has to indicate that they support Optional, they also indicate that they know about synthetic oneofs and have updated their codegen appropriately. This means the PGS AST can stay "correct" (i.e. actually reflecting the descriptor). We can/should still provide additional helpers though, as suggested in the doc. 

This treatment also inherits the positives of the synthetic oneof approach,
>Since oneof fields in proto3 already track presence, existing proto3 reflection-based algorithms should correctly preserve presence for proto3 optional fields with no code changes. For example, the JSON and TextFormat parsers/serializers in C++ and Java did not require any changes to support proto3 presence. This is the major benefit of synthetic oneofs.

**Comment by sarthak40** [comment]
@dkunitsk thanks for looking into this!

I really like the idea for the users to be able to define (through an `InitOption`) if their plugin supports `proto3 optional` or not. That shouldn't be hard to implement.

I'll work on the updated helpers later today as well and we can get this moving.

**Comment by sarthak40** [comment]
@dkunitsk polite ping, have you had a chance to review this yet?

**Comment by sarthak40** [comment]
I now have a version of PGV rendering with these changes locally!

@dkunitsk @akonradi if one of you could get this reviewed we can start on resolving https://github.com/envoyproxy/protoc-gen-validate/issues/431 :+1:

**Comment by akonradi** [comment]
I'm not familiar enough with how PGS abstracts over proto2&3 to have opinions on the API (mostly regarding `OneOf` vs `RealOneOf` vs `SyntheticOneOf`) nor am I a maintainer on this project (just PGV). LGTM and looking forward to getting to use this functionality in PGV though.

**Comment by dkunitsk** [comment]
Thanks for these changes. Will review in the morning.

**Comment by sarthak40** [comment]
@dkunitsk did you get a chance to review?

File: init_option.go [hunk 1]
```diff
@@ -47,3 +48,12 @@ func FileSystem(fs afero.Fs) InitOption { return func(g *Generator) { g.persiste
 func BiDirectional() InitOption {
 	return func(g *Generator) { g.workflow = &onceWorkflow{workflow: &standardWorkflow{BiDi: true}} }
 }
+
+// SupportProto3Optional adds support for proto3 field presence.
+// See: https://github.com/protocolbuffers/protobuf/blob/master/docs/implementing_proto3_presence.md#signaling-that-your-code-generator-supports-proto3-optional
```
Comment (dkunitsk) [inline init_option.go:53]: point to a commit or version instead of master, as that can change

File: proto.go [hunk 2]
```diff
@@ -13,10 +13,10 @@ const (
...
 	Proto2 Syntax = ""
 
-	// Proto3 syntax only allows for optional fields, but defaults to the zero
-	// value of that particular type. Most of the field types in the generated go
-	// structs are value types.
-	// See: https://developers.google.com/protocol-buffers/docs/proto3
+	// Proto3 syntax permits the use of "optional" field presence. Non optional fields default to the zero
+	// 	value of that particular type if not defined.
+	// Most of the field types in the generated go structs are value types.
+	// See: https://github.com/protocolbuffers/protobuf/blob/master/docs/field_presence.md#presence-in-proto3-apis
```
Comment (dkunitsk) [inline proto.go:19]: Same nit about master -> version url

File: protoc-gen-debug/main.go [hunk 3]
```diff
@@ -41,8 +42,10 @@ func main() {
 		log.Fatal("unable to write request to disk: ", err)
 	}
 
-	data, err = proto.Marshal(&plugin_go.CodeGeneratorResponse{})
-	if err != nil {
+	var supportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)
+	if data, err = proto.Marshal(&plugin_go.CodeGeneratorResponse{
```
Comment (dkunitsk) [inline protoc-gen-debug/main.go:46]: IIUC this again makes PGS by default claim to support `CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL`. My suggestion was to create a new `InitOption` type (in `init_option.go`), which will set the generator's persister's supportedFeatures variable. This gives full control to the user.

Comment (dkunitsk) [reply protoc-gen-debug/main.go:46]: see https://github.com/lyft/protoc-gen-star/blob/master/init_option.go#L43

File: field.go [hunk 4]
```diff
@@ -56,11 +69,31 @@ func (f *field) SourceCodeInfo() SourceCodeInfo               { return f.info }
...
+	}
+
+	if f.Syntax() == Proto3 && !f.Optional() && !(f.Type().IsEmbed() || f.InRealOneOf()) {
+		return false
+	}
+
+	return true
+}
+
+func (f *field) Optional() bool {
```
Comment (dkunitsk) [inline field.go:90]: To be extra clear and follow the guidelines more precisely, perhaps we should call this HasOptionalKeyword()

**Review by dkunitsk — COMMENTED** [review]
My apologies for being late in reviewing this. This seems to be very nearly there. Please take a look at my feedback and let me know what you think. Many of these comments I'm happy to discuss further.

**Comment by ash2k** [comment]
Would be awesome to get this merged to help resolve https://github.com/envoyproxy/protoc-gen-validate/issues/431

**Comment by sarthak40** [comment]
@dkunitsk thanks for the review!

I haven't been able to find the time to work on this, but i'll see if I can muster up something this week.

**Review by xmlking — DISMISSED** [review]

File: field.go [hunk 5]
```diff
@@ -56,11 +69,31 @@ func (f *field) SourceCodeInfo() SourceCodeInfo               { return f.info }
...
+	if f.Syntax() == Proto3 {
```
[the remark this answers is not in the document]
Comment (sarthak40) [reply field.go:91]: Both `proto2` & `proto3` support explicit presence.

I can see why you would say that, but since presence here is a property of a field and not any particular syntax, that function wouldn't be particularly useful or accurate imo.

File: protoc-gen-debug/main.go (hunk 3 above)
Comment (sarthak40) [reply protoc-gen-debug/main.go:46]: I've changed the behaviour in `init_option.go`, though i've left it as-is in `protoc-gen-debug` as the latter is a dev tool.

**Comment by sarthak40** [comment]
@dkunitsk ICYMI, this is ready for review 👍

**Comment by nikoncode** [comment]
Guys, may I ask status of this MR?

We are building a new transport stack in our company and want to combine both validation and presence tracking support in our proto definitions. And this seems to block validation support and all our concepts.

cc: @xmlking, @glerchundi, @dkunitsk

**Comment by sarthak40** [comment]
@dkunitsk if you could please take another look at this, i'd appreciate it.

File: .travis.yml [hunk 6]
```diff
@@ -4,8 +4,7 @@ go_import_path: github.com/lyft/protoc-gen-star
 
 env:
   matrix:
-    - PROTOC_VER="3.5.1"
```
Comment (dkunitsk) [inline .travis.yml:7]: could we please keep the other ones and just add on 3.16.0

File: field.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (dkunitsk) [reply field.go:99]: Agree, thanks.

File: field_test.go [hunk 7]
```diff
@@ -99,6 +99,59 @@ func TestField_OneOf(t *testing.T) {
...
+	f.msg = dummyMsg()
+	f.addType(&scalarT{})
+	assert.False(t, f.HasPresence())
+
+	opt := true
+	f.desc = &descriptor.FieldDescriptorProto{Proto3Optional: &opt}
+	assert.True(t, f.HasPresence())
+}
+
+func TestField_Optional(t *testing.T) {
```
Comment (dkunitsk) [inline field_test.go:134]: nit: `TestField_HasOptionalKeyword`

File: field_test.go [hunk 8]
```diff
@@ -194,3 +247,23 @@ func dummyField() *field {
 	f.addType(t)
 	return f
 }
+
+func dummyOneOfField(synthetic bool) *field {
```
Comment (dkunitsk) [inline field_test.go:251]: 👌

File: field_type.go [hunk 9]
```diff
@@ -84,7 +83,7 @@ func (s *scalarT) Element() FieldTypeElem { return nil }
 func (s *scalarT) Key() FieldTypeElem     { return nil }
 
 func (s *scalarT) IsOptional() bool {
-	return !s.fld.Syntax().SupportsRequiredPrefix() || s.ProtoLabel() == Optional
+	return s.fld.HasOptionalKeyword()
```
Comment (dkunitsk) [inline field_type.go:86]: This would make all proto3 fields without presence suddenly become `IsOptional() == false` which is very backwards incompatible. 

Proto3 optional label is not the same as proto2. The proto2 label means "this field is not required" whereas the proto3 label means "this field is still not required, but it has explicit presence semantics". 

This `IsOptional` in particular is referring to the field not being required, which is not affected by the explicit presence semantics. So IIUC this method does not need to change.

File: field.go [hunk 10]
```diff
@@ -61,6 +74,34 @@ func (f *field) Type() FieldType                              { return f.typ }
...
+	if f.InOneOf() {
+		return true
+	}
+
+	if f.Type().IsEmbed() {
+		return true
+	}
+
+	if f.HasOptionalKeyword() ||
+		(f.Syntax() == Proto2 && !f.Type().IsRepeated() && !f.Type().IsMap()) {
```
Comment (dkunitsk) [inline field.go:91]: nit I would rewrite this as:

```
if (!f.Type().IsRepeated() && !f.Type().IsMap()) {
	if f.Syntax() == Proto2 { 
		return true
	}
    return f.HasOptionalKeyword()
}
```

No deep reason, it just made more sense to me. LMK if you disagree.

File: lang/go/type_name_test.go [hunk 11]
```diff
@@ -88,19 +88,40 @@ func TestType(t *testing.T) {
 		{"Proto3.string", "string"},
 		{"Proto3.bytes", "[]byte"},
 		{"Proto3.enum", "Proto3_Enum"},
-		{"Proto3.ext_enum", "ptype.Syntax"},
+		{"Proto3.ext_enum", "typepb.Syntax"},
```
Comment (dkunitsk) [inline lang/go/type_name_test.go:91]: hmm why did this work before...

File: oneof.go [hunk 12]
```diff
@@ -52,6 +56,12 @@ func (o *oneof) Descriptor() *descriptor.OneofDescriptorProto { return o.desc }
 func (o *oneof) Message() Message                             { return o.msg }
 func (o *oneof) setMessage(m Message)                         { o.msg = m }
 
+func (o *oneof) IsSynthetic() bool {
+	return o.Syntax() == Proto3 &&
+		len(o.flds) == 1 &&
+		!o.flds[0].InRealOneOf()
```
Comment (dkunitsk) [inline oneof.go:62]: nit: may i recommend inlining `!f.desc.GetProto3Optional()` here. Just makes it more immediately clear what's going on.

File: proto.go [hunk 13]
```diff
@@ -13,10 +13,10 @@ const (
 	// See: https://developers.google.com/protocol-buffers/docs/proto
 	Proto2 Syntax = ""
 
-	// Proto3 syntax only allows for optional fields, but defaults to the zero
-	// value of that particular type. Most of the field types in the generated go
-	// structs are value types.
-	// See: https://developers.google.com/protocol-buffers/docs/proto3
+	// Proto3 syntax permits the use of "optional" field presence. Non optional fields default to the zero
```
Comment (dkunitsk) [inline proto.go:16]: I think this explanation slightly confuses optionality as the opposite of requiredness versus optionality as having explicit presence. Even with explicit presence it is true that `Proto3 syntax only allows for optional fields`.

I would recommend rewording to something like 
`Proto3 syntax only allows for optional fields, and it defaults to the zero value of that particular type (unless experimental support for explicit presence tracking for singular proto3 fields is used, see <link>). `

File: protoc-gen-debug/main.go (hunk 3 above)
Comment (dkunitsk) [reply protoc-gen-debug/main.go:46]: Makes sense to me - but perhaps leave a comment to that effect.

File: .travis.yml (hunk 6 above)
Comment (dkunitsk) [reply .travis.yml:7]: You may need to use https://mickey.dev/posts/go-build-tags-testing/ (for example) to mark which tests apply to the older protoc versions versus newer. But I think I really don't want to lose test coverage for the old versions, esp since it should be relatively easy to keep them. WDYT.

**Comment by dkunitsk** [comment]
@sarthak40 huge thank you for the diff. I left some last comments. I am confident that after one more iteration it will be fully there. 

I know most of the delay has been on my end, but I can promise that once you address the above, I will re-review and merge right away.

**Comment by sarthak40** [comment]
@dkunitsk thanks for the review!

Let me take a crack at your comments over the weekend and get the ball rolling!

File: field_test.go [hunk 14]
```diff
@@ -99,6 +99,59 @@ func TestField_OneOf(t *testing.T) {
...
+	f.desc = &descriptor.FieldDescriptorProto{Proto3Optional: &opt}
+	assert.True(t, f.HasPresence())
+}
+
+func TestField_Optional(t *testing.T) {
+	t.Parallel()
+
+	optLabel := descriptor.FieldDescriptorProto_LABEL_OPTIONAL
+
+	f := &field{msg: &msg{parent: dummyFile()}}
```
[the remark this answers is not in the document]
Comment (sarthak40) [reply field_test.go:139]: not in this case, just being more explicit

File: lang/go/type_name_test.go (hunk 11 above)
Comment (sarthak40) [reply lang/go/type_name_test.go:91]: i'm not actually sure myself on this one, a bit perplexed myself

File: oneof.go (hunk 12 above)
Comment (sarthak40) [reply oneof.go:62]: Hmm, I think using `.GetProto3Optional()` (which is an explicit property of  a `Field`) outside the context of a field will be more confusing over time.

From the perspective of a Synthentic OneOf, I think it reads fine right?
- Syntax is Proto3
- OneOf contains exactly one field (an extra semantic check)
- The singular field is not considered to be in a `RealOneOf`

WDYT?

File: proto.go (hunk 13 above)
Comment (sarthak40) [reply proto.go:16]: `(unless experimental support for explicit presence..`

According to [protobuf v3.15.0](https://github.com/protocolbuffers/protobuf/releases/tag/v3.15.0) field presence support in proto3 is no longer experimental.

File: .travis.yml (hunk 6 above)
Comment (sarthak40) [reply .travis.yml:7]: Hmm, this is turning out to be tricker than I anticipated.

I need to first edit the makefiles to ensure they don't compile the proto3 optional bits, then ensure I add the build tags for the golang tests themselves..

I am testing by isolating the testing harness into `testdata/proto3_presence` for now, but let me know if you prefer a different name.

**Comment by sarthak40** [comment]
@dkunitsk addressed most of your comments, ready for round 3 👍

**Comment by glerchundi** [comment]
This is really close, great job @sarthak40!! Ultra friendly ping ICYMI @dkunitsk, and hoping that it's not gonna take too much of your time 🤞

**Comment by sarthak40** [comment]
@dkunitsk friendly ping please

**Review by dkunitsk — APPROVED** [review]

**Comment by dkunitsk** [comment]
@sarthak40 brilliant work. Thank you for pushing this through. It is available here: https://github.com/lyft/protoc-gen-star/releases/tag/v0.6.0. 

One ask: do you think you can make a README change to tell folks how to use this and just to advertise the existence of support for field presence in PGS?

**Comment by sarthak40** [comment]
Fantastic! Likewise, thanks a lot for the reviews, we got it there in the end 😎.

I will be looking at PGV code over the weekend to get that moving now, but can also submit a README update for PGS at the same time.
